Removed reflection access and enabled extensibility
Deep-Winter/rrule-parser.net pull request #7
Opened 2021-07-05 17:16 UTC by Frisch12

By removing some reflection accesses the code will be more save to execute. Furthermore by saving token names inside a dictionary users of this library can implement their own token types.

2021-07-06 11:29 UTC, Deep-Winter requested changes
#7 möchte ich nicht übernehmen, da ich mich hier an das Original halten möchte.

2021-07-06 11:29 UTC, Deep-Winter approved these changes
Okay danke

2021-07-06 11:30 UTC, Deep-Winter approved these changes
ok

2021-07-06 11:30 UTC, Deep-Winter approved these changes
ok

2021-07-06 11:31 UTC, Deep-Winter approved these changes
konnte ich nachvollziehen. Passt. Danke!

2021-07-06 11:31 UTC, Deep-Winter approved these changes
ok

2021-07-06 11:37 UTC, Deep-Winter requested changes
Okay sorry, dachte der Kommentar wäre pro commit. Also die meisten Änderungen und der Bugfix sind okay. Danke dafür. Aber den Umbau von Enum auf Dictionary möchte ich nicht übernehmen, um mich ans Original zu halten. Der müsste bitte wieder raus.
Wie geht's dir? Lange nichts gehört.

2021-07-06 11:43 UTC, Frisch12 commented
Alles gut :) Du kannst auch im kompletten Change (Files Changed) einzelne Zeilen kommentieren. 
Nehme ich wieder raus, kein Problem :) 

Ganz gut und selbst? Wenn du ein bisschen quatschen willst (muss ja nicht hier sein) schreib mir doch ne Mail oder ne WhatsApp, falls du meine Nummer hast.

2021-07-06 11:48 UTC, Frisch12 commented
Done!

2021-07-08 09:13 UTC, Deep-Winter approved these changes
Alles klar danke

2021-07-08 09:13 UTC, merged